config/routes.rb
Rails.application.routes.draw do
	
  resources :likes
	root to: 'users#new'
	
	resources :contacts, only: [:new, :create]

	resources :team, only: [:index]

	resources :gosssips do
		resources :likes, only: [:create, :destroy]
	end

	resources :users

	resources :cities

	resources :tags, only: [:new, :create, :destroy]

	resources :comments, except: [:new, :index, :show]
	
	resources :sessions, only: [:new, :create, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
        validates :name, presence: true, word: true
        validates :zip_code, presence: true, text: true
	
	has_many :users        #City en relation 1-N avec User

end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence:true, text: true
    
    belongs_to :user
    belongs_to :gosssip
end

app/models/gosssip.rb
class Gosssip < ApplicationRecord
	validates :title, presence: true, text: true, length: {maximum: 14}
	validates :content, presence: true, text: true
	validates :user_id, presence: true, on: create
		

	belongs_to :user
	has_many :tag_lists
	has_many :tags, through: :tag_lists
	has_many :comments
	has_many :users, through: :comments
	has_many :likes, dependent: :destroy
	has_many :users, through: :likes

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :gosssip
	belongs_to :user

        def self.gossips(user_id)
            @likes_gossips = Array.new
            @likes = Like.where(user_id: user_id)
            @likes.each do |like|
                @likes_gossips << like.gosssip_id
            end
            return @likes_gossips
        end

end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title, presence: true
	#, format: { with: /\A$#[\w\_]{2,20}\z/, message: "format #hashtag entre 2 et 10 caracteres" }

	has_many :tag_lists
	has_many :gosssips, through: :tag_lists
end

app/models/tag_list.rb
class TagList < ApplicationRecord
	belongs_to :gosssip
	belongs_to :tag

end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Merci d'inserer un email valide" }
	validates :first_name, presence: true, word: true
	validates :last_name, word: true, on: :update
	validates :age, format: {with: /[0-9]{2}/, message: "l'age doit etre ecrit avec 2 chiffres"}, on: :update
	validates :description, text:true, on: :update
	validates :city_id, text: true, on: :update
	validates :password, presence: true, length: {minimum: 6} 
		
	has_secure_password
		
	belongs_to :city
	has_many :gosssips
	has_many :comments
	has_many :gosssips, through: :comments
	has_many :likes, dependent: :destroy
	has_many :gosssips, through: :likes

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]


  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show

  end

  # GET /comments/new
 

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
   # @gossip = Gosssip.find(@comment.gosssip_id)
  end

  # POST /comments
  def create

    @comment = Comment.new(comment_params)
    @comment.gosssip_id = params[:gossip]
    @comment.user_id = current_user.id
       
      if @comment.save
        redirect_to gosssip_path(params[:gossip]), flash: {success: " Commentaire ajoute" }
      else
       redirect_to gosssip_path(params[:gossip]), flash: {danger: " Les commentaires ne peuvent pas avoir de caracteres speciaux" }

      end
    
  end

  # PATCH/PUT /comments/1
  def update

    if @comment.update(comment_params)
      redirect_to gosssip_path(@comment.gosssip_id), flash: {success: " Commentaire modifie" }
    else
      render 'edit'
    end
    
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
      redirect_to gosssips_path, flash: {success: " Le commentaire a ete detruit" }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      return params.require(:comment).permit(:content)
    end

    def authenticate_user
      unless current_user.id == @comment.user_id 
        flash[:danger] = "Acces restreint"
        redirect_to gosssips_path
      end
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :find_gossip


  # POST /likes
  # POST /likes.json
  def create
    if already_liked?
      flash[:danger] = "You can't like more than once"
    else
      @gossip.likes.create(user_id: current_user.id)
    end
    redirect_to gosssips_path

  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    find_like
    @like.destroy
     redirect_to gosssip_path(@gossip.id)
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def already_liked?
      Like.where(user_id: current_user.id, gosssip_id: params[:gosssip_id]).exists?
    end

    def find_gossip
      @gossip = Gosssip.find(params[:gosssip_id])
    end

    def find_like
       @like = Like.where(user_id: current_user.id, gosssip_id: params[:gosssip_id]).first
      
   end

    # Never trust parapmeters from the scary internet, only allow the white list through.
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def new
    end

    def create 
    end

    def destroy 
    end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    skip_before_action :only_signed_in, only: [:index]

    def index

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create]


  def index
     @users = User.all
	
	# Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
        @user = User.find(params[:id])
        @gossips_user = Gosssip.where(user: @user)
        @gossips_likes = Like.gossips(current_user.id)

	
	# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
	@user = User.new
      	
	# Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to gosssips_path, flash: {success: "Bienvenue #{@user.first_name}" }
   
     else
        render 'new'
        #redirect_to new_session_path
     end

  end

  def edit
	@user = User.find(params[:id])
	
	# Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
	@user = User.find(params[:id])
        @user.update(user_params)
	
	redirect_to user_path(@user.id)
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
        @user = User.find(params[:id])
	@user.destroy	

	redirect_to root_path
      	
      	# Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

	private

	def user_params
		return params.require(:user).permit(:first_name, :city_id, :email, :password )
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_helper.rb
module DynamicHelper
end

app/helpers/gosssips_helper.rb
module GosssipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id].nil?
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<%= form_for :comment, url: comments_path do |f| %>

				<div class="control-group">
                   	<div class="form-group floating-label-form-group controls">
						<%= f.label :content, "Comment" , class: 'col-md-4 control-label'%>
                        <%= f.text_field :content, class:'form-control' %>

						<p class="help-block text-danger"></p>
						<%= hidden_field_tag(:gossip, "1") %>

	           		 </div>
				</div>
			
				<div id="success"></div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary" id="sendMessageButton">Add a comment</button>
					</div>
				<%end%>

app/views/comments/edit.html.erb
<!-- Masthead -->
<header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Heading -->
                <h1 class="masthead-heading text-uppercase mb-0"> Editer mon commentaire</h1>
        </div>
</header>

<% if @comment.errors.any? %>
        <div class="alert alert-danger">
        <% @comment.errors.full_messages.each do |message| %>

                <%="#{message}." %>

        <%end%>
        </div>
<%end%>

<div class="container mt-5">
        <%= form_for @comment do |f| %>
                <div class="form-group">
                <label> Contenu du commentaire </label>
                <%= f.text_area :content, class: 'form-control' %>
        </div>
	<div class="form-group">
                <button type="submit" class= "btn btn-primary"> Modifier mon commentaire </button>
                <a class="btn btn-danger btn-sm" href="<%= comment_path(@comment.id) %>" role="button" data-confirm="Attention la suppression est irreversible" data-method="DELETE">Supprimer le commentaire</a>

        </div>
        
        <%end%>
</div>