config/routes.rb
Rails.application.routes.draw do
	
  resources :likes
	root to: 'users#new'
	
	resources :contacts, only: [:new, :create]

	resources :team, only: [:index]

	resources :gosssips do
		resources :likes, only: [:create, :destroy]
	end

	resources :users

	resources :cities

	resources :tags, only: [:new, :create, :destroy]

	resources :comments, except: [:new, :index, :show]
	
	resources :sessions, only: [:new, :create, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Merci d'inserer un email valide" }
	validates :first_name, presence: true, word: true
	validates :last_name, word: true, on: :update
	validates :age, format: {with: /[0-9]{2}/, message: "l'age doit etre ecrit avec 2 chiffres"}, on: :update
	validates :description, text:true, on: :update
	validates :city_id, text: true, on: :update
	validates :password, presence: true, length: {minimum: 6} 
		
	has_secure_password
		
	belongs_to :city
	has_many :gosssips
	has_many :comments
	has_many :gosssips, through: :comments
	has_many :likes, dependent: :destroy
	has_many :gosssips, through: :likes

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create]


  def index
     @users = User.all
	
	# Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
        @user = User.find(params[:id])
        @gossips_user = Gosssip.where(user: @user)
        @gossips_likes = Like.gossips(current_user.id)

	
	# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
	@user = User.new
      	
	# Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to gosssips_path, flash: {success: "Bienvenue #{@user.first_name}" }
   
     else
        render 'new'
        #redirect_to new_session_path
     end

  end

  def edit
	@user = User.find(params[:id])
	
	# Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
	@user = User.find(params[:id])
        @user.update(user_params)
	
	redirect_to user_path(@user.id)
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
        @user = User.find(params[:id])
	@user.destroy	

	redirect_to root_path
      	
      	# Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

	private

	def user_params
		return params.require(:user).permit(:first_name, :city_id, :email, :password )
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="body-blue">
<body>

  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign In</h5>
            <% if @user.invalid? %>
                <div class="alert alert-danger">
                    <% @user.errors.full_messages.each do |message| %>
                        <ul>
                        <%="#{message}." %>
                        </ul>
                <%end%>
                </div>
            <%end%>
            <%= form_for @user do |f|%>

            <form class="form-signin">
                <%= f.label :first_name, "First name" %>
                <div class="form-label-group">
                    <%= f.text_field :first_name, class:'form-control' %>   
                </div>
                <%= f.label :city, "City" %>
                <div class="form-label-group">
                    <%= f.collection_select :city_id, City.order(:name),:id,:name, include_blank: true %>
                </div>                
                
                <%= f.label :email, "Email address" %>
                <div class="form-label-group">
                    <%= f.text_field :email, class:'form-control' %>
                   
                </div>
                <%= f.label :password, "Password" %>
              <div class="form-label-group">
                 <%= f.password_field :password, class:'form-control' %>
                
              </div>

                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>

               <%end %>

              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</body>
</div>

app/views/users/new.html.erb
<div class="body-blue">
<body>

  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign In</h5>
            <% if !@user[:first_name].nil? %>
                <div class="alert alert-danger">
                    <% @user.errors.full_messages.each do |message| %>
                        <ul>
                        <%="#{message}." %>
                        </ul>
                <%end%>
                </div>
            <%end%>
            <%= form_for @user do |f|%>

            <form class="form-signin">
                <%= f.label :first_name, "First name" %>
                <div class="form-label-group">
                    <%= f.text_field :first_name, class:'form-control' %>   
                </div>
                <%= f.label :city, "City" %>
                <div class="form-label-group">
                    <%= f.collection_select :city_id, City.order(:name),:id,:name, include_blank: true %>
                </div>                
                
                <%= f.label :email, "Email address" %>
                <div class="form-label-group">
                    <%= f.text_field :email, class:'form-control' %>
                   
                </div>
                <%= f.label :password, "Password" %>
              <div class="form-label-group">
                 <%= f.password_field :password, class:'form-control' %>
                
              </div>

                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>

               <%end %>

              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</body>
</div>

app/views/users/show.html.erb
<!-- Masthead -->
<header class="masthead bg-primary text-white text-center">
	<div class="container d-flex align-items-center flex-column">
		<!-- Masthead Heading -->
		<h1 class="masthead-heading text-uppercase mb-0"> Fiche auteur</h1>
	</div>
</header>

<!-- Portfolio Section -->
<section class="page-section portfolio" id="portfolio">
	<div class="container">
		<!-- Portfolio Section Heading -->
		<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Auteur :  <%= "#{@user.first_name}" %> </p></h2>
		<!-- Icon Divider -->
		<div class="divider-custom">
			<div class="divider-custom-line"></div>
		<div class="divider-custom-icon">
        		<i class="fas fa-star"></i>
		</div>
			<div class="divider-custom-line"></div>
		</div>


	
	
		<div class="row">
			<div class="col-8">
				<div class="row">
				        <% @gossips_user.each do |gossip| %>
		     			 <div class="card m-2" style="width: 16rem;">
			    			<div class="card-body">
				  			 	<h5 class="card-title"> <%= gossip.title %></h5>
  				  				<h6 class="card-subtitle mb-2 text-muted">Auteur : <%= gossip.user.first_name %></h6>
              					<h6 class="card-subtitle mb-2 text-muted"> <%= "#{gossip.comments.count} commentaires / " %> <%= "#{gossip.likes.count} " %> <i class="fas fa-heart"></i>  </h6>
             					 <% if !@gossips_likes.include?(gossip.id) %>
                					<%= form_for :like, url: gosssip_likes_path(gossip) do |f| %>
				        			<button class="">  <i class="fas fa-heart"></i> Like</i> </button>
				       				 <%end%> 
             					 <%end%>
            				  <%= link_to "Afficher le detail du gossip", gosssip_path(gossip.id) %>
			     			</div>
  		   				 </div>
	    				  <% end %>
			      </div>
			</div>
  			<div class="col-4">
		      		<div class="jumbotron">
					<img class="masthead-avatar mb-5" src="/images/avatar.svg" alt="">
					<p class="lead"><%= "#{@user.first_name} #{@user.last_name}, #{@user.age} ans, a #{@user.city.name}" %></p>
			                <hr class="my-4">
        	        	        	<p> <%= @user.description %></p>
	                	        	
					</hr>
	                                <hr class="my-4">
					<p> Contact <%= @user.email %> </p>
					</hr>
				</div>
			</div>
		</div>
</section>