config/routes.rb
Rails.application.routes.draw do
	
  resources :likes
	root to: 'users#new'
	
	resources :contacts, only: [:new, :create]

	resources :team, only: [:index]

	resources :gosssips do
		resources :likes, only: [:create, :destroy]
	end

	resources :users

	resources :cities

	resources :tags, only: [:new, :create, :destroy]

	resources :comments, except: [:new, :index, :show]
	
	resources :sessions, only: [:new, :create, :destroy]


end

app/models/gosssip.rb
class Gosssip < ApplicationRecord
	validates :title, presence: true, text: true, length: {maximum: 14}
	validates :content, presence: true, text: true
	validates :user_id, presence: true, on: create
		

	belongs_to :user
	has_many :tag_lists
	has_many :tags, through: :tag_lists
	has_many :comments
	has_many :users, through: :comments
	has_many :likes, dependent: :destroy
	has_many :users, through: :likes

end

app/controllers/gosssips_controller.rb
class GosssipsController < ApplicationController

	before_action :set_gossip, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user, only: [:edit, :update, :destroy]

	#code de la methode private set_gossip qui va se derouler avant les methodes show, edit, update et destroy

  def index
	@gossips = Gosssip.all
	@gossips_likes = Like.gossips(current_user.id)
	#@likes = Like.where(user_id: current_user.id)

	# Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
	@gossip = Gosssip.find(params[:id])
	@comments = Comment.where(gosssip: @gossip)
	@comment = Comment.new
	puts @like = Like.where(user_id: current_user.id, gosssip_id: @gossip)

	# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
	puts logged_in?
    	@gossip = Gosssip.new
		@tags = Tag.all
	  # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
   	@gossip = Gosssip.new(gossip_params)
	@gossip.user = User.find_by(id: current_user.id)
	@gossip.tags = Tag.where(id: params[:tag_ids])

	if  @gossip.save
		redirect_to gosssips_path, flash: {success: "Gossip cree avec success" }

	else
		@tags = Tag.all
		render 'new'

	end
	  # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit
	  # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
	  if @gossip.update(gossip_params)
 	 	flash[:success] = "Gossip modifie avec success"	
	 	redirect_to gosssip_path(@gossip.id)
	  else
		render 'edit'
	  end
		
		# Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
	  @gossip.destroy
          flash[:danger] = "Gossip supprime avec success" 

	  redirect_to gosssips_path
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

	private

	def gossip_params
		return params.require(:gosssip).permit(:title, :content)
	end
	
	def set_gossip
          @gossip = Gosssip.find(params[:id])
	end

	def authenticate_user
		unless current_user.id == @gossip.user.id
		  flash[:danger] = "Acces restreint"
		  redirect_to gosssips_path
		end
	  end

end

app/helpers/gosssips_helper.rb
module GosssipsHelper
end

app/views/gosssips/_form.html.erb
<!-- Masthead -->
<header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Heading -->
                <h1 class="masthead-heading text-uppercase mb-0"> Creer un Gossip</h1>
        </div>
</header>

<% if @gossip.errors.any? %>
        <div class="alert alert-danger">
        <% @gossip.errors.full_messages.each do |message| %>

                <%="#{message}." %>

        <%end%>
        </div>
<%end%>

<div class="container mt-5">

        <%= form_for @gossip do |f| %>
        
		<div class="form-group">
                        <label> Titre de l'article </label>
                        <%= f.text_field :title, class: 'form-control' %>
                </div>
                <div class="form-group">
                        <label> Contenu du Gossip </label>
                        <%= f.text_area :content, class: 'form-control' %>
                </div>
		<div class="input-group m-3 ">
			<label> Selectionner un ou plusieurs tags : </label>
	            <%= select_tag "tag_ids", options_from_collection_for_select(Tag.order(:title), "id", "title"), multiple: true, class: 'ml-5' %>

		</div>
		<div class="form-group">
                       	<button type="submit" class= "btn btn-primary"> Ajouter mon Gossip </button>
                </div>

		</div>
        <%end%>
</div>

app/views/gosssips/edit.html.erb
<%= render 'form', gosssip: @gosssip %>

app/views/gosssips/index.html.erb
  <!-- Masthead -->
  <header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">

      <!-- Masthead Avatar Image -->
      <img class="masthead-avatar mb-5" src="/images/avatar.svg" alt="">

      <!-- Masthead Heading -->
      <h1 class="masthead-heading text-uppercase mb-0"> Bienvenue sur The Gossip Project - <%=current_user.first_name %> !</h1>

      <!-- Masthead Subheading -->
      <p class="masthead-subheading font-weight-light mb-0"> Realised by David.T</p>

    </div>
  </header>

  <!-- Portfolio Section -->
  <section class="page-section portfolio" id="portfolio">
    <div class="container">

      <!-- Portfolio Section Heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Liste des Gossips</h2>

      <!-- Icon Divider -->
      <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon">
          <i class="fas fa-star"></i>
        </div>
        <div class="divider-custom-line"></div>
      </div>

      <div class="container mb-3">
	      <%= link_to "Creer un nouveau gossip", new_gosssip_path, class: 'btn btn-primary' %>
      </div>
	
      <!-- Cards Gossips -->
      <div class="row">
 	      <% @gossips.each do |gossip| %>
		      <div class="card m-2" style="width: 16rem;">
			    	<div class="card-body">
				  	  <h5 class="card-title"> <%= gossip.title %></h5>
  				  	<h6 class="card-subtitle mb-2 text-muted">Auteur : <%= gossip.user.first_name %></h6>
              <h6 class="card-subtitle mb-2 text-muted"> <%= "#{gossip.comments.count} commentaires / " %> <%= "#{gossip.likes.count} " %> <i class="fas fa-heart"></i>  </h6>
              <% if !@gossips_likes.include?(gossip.id) %>
                <%= form_for :like, url: gosssip_likes_path(gossip) do |f| %>
				        	<button class="">  <i class="fas fa-heart"></i> Like</i> </button>
				        <%end%> 
              <%end%>
              <%= link_to "Afficher le detail du gossip", gosssip_path(gossip.id) %>
			      </div>
  		    </div>
	      <% end %>
      </div>
    </div>
  </section>

app/views/gosssips/new.html.erb
<%= render 'form', gosssip: @gosssip %>

app/views/gosssips/show.html.erb
<!-- Masthead -->
<header class="masthead bg-primary text-white text-center">
	<div class="container d-flex align-items-center flex-column">
		<!-- Masthead Heading -->
		<h1 class="masthead-heading text-uppercase mb-0"> Fiche du Gossip</h1>
	</div>
</header>
<!-- Portfolio Section -->
<section class="page-section portfolio" id="portfolio">
	<div class="container">
		<!-- Portfolio Section Heading -->
		<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Gossip :  <%= "#{@gossip.title}" %> </p></h2>
		<!-- Icon Divider -->
		<div class="divider-custom">
		        <div class="divider-custom-line"></div>
	        <div class="divider-custom-icon">
        		<i class="fas fa-star"></i>
	        </div>
        		<div class="divider-custom-line"></div>
      </div>


	<div class="jumbotron">
		<p class="lead"><%= @gossip.content %></p>
		<hr class="my-4">
			<p>Ce gossip a ete ecrit par <%= @gossip.user.first_name %>, qui vit a <%= @gossip.user.city.name %> et la cree le <%= @gossip.created_at %> </p>
			<p> Tags associes : 
			<% @gossip.tags.each do |tag|%>
				<%=tag.title%> 
			<%end %>
			</p>
			<a class="btn btn-primary btn-lg" href="<%= user_path(@gossip.user.id) %>" role="button">Afficher la page de l'auteur</a>
			<a class="btn btn-primary btn-lg" href="<%= city_path(@gossip.user.city.id) %>" role="button">Afficher la page de la ville de l'auteur</a>
			<% if current_user.id == @gossip.user.id %>
				<a class="btn btn-secondary btn-lg" href="<%= edit_gosssip_path(@gossip.id) %>" role="button">Modifier le gossip</a>
	   			<a class="btn btn-danger btn-lg" href="<%= gosssip_path(@gossip.id) %>" role="button" data-confirm="Attention la suppression est irreversible" data-method="DELETE">Supprimer le gossip</a>
			<%end%>

			<% if @like.empty? %>
				<%= form_for :like, url: gosssip_likes_path(@gossip) do |f| %>
					<button class="btn br3 bg-orange9 ph4 pv3 lh0 bt bl bw2 b--black-20 white tc">  <i class="fas fa-heart"></i> Like</i> </button>
				<%end%>
			<%else%>
				<a class="btn br3 bg-orange9 ph4 pv3 lh0 bt bl bw2 b--black-20 white tc" href="<%= gosssip_like_path(@gossip.id) %>" role="button" data-method="DELETE">Supprimer le gossip</a>
			<%end%>

		</hr>
	</div>

<div class="container">
		<!-- Portfolio Section Heading -->
		<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0"> Comments :  <%= "#{@gossip.comments.count} comments" %> </p></h2>
	<div class="divider-custom">
		        <div class="divider-custom-line"></div>
	        <div class="divider-custom-icon">
        		<i class="fas fa-star"></i>
	        </div>
        		<div class="divider-custom-line"></div>
      </div>
	  
<% if @comment.errors.any? %>
        <div class="alert alert-danger">
        <% @comment.errors.full_messages.each do |message| %>

                <%="#{message}." %>

        <%end%>
        </div>
<%end%>


		<%= form_for :comment, url: comments_path do |f| %>

				<div class="control-group">
                   	<div class="form-group floating-label-form-group controls">
						<%= f.label :content, "Comment" , class: 'col-md-4 control-label'%>
                        <%= f.text_field :content, class:'form-control' %>

						<p class="help-block text-danger"></p>
						<%= hidden_field_tag(:gossip, @gossip.id) %>

	           		 </div>
				</div>
			
				<div id="success"></div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary" id="sendMessageButton">Add a comment</button>
					</div>
				<%end%>


  <!-- Cards Gossips -->
     	<table class="table">
		 	<thead> 
				<tr>
					<th class= "" >  Commentaires</th>
					<th class= "" >  </th>
					<th class= "" >  </th>

				</tr>
			</thead>
				<tbody>
					
					 <% @comments.each do |comment| %>
					<tr>
					<td>
						<p class="lead"><%= comment.content %></p>
					</td>
					<td>
						<p> Ecrit par <%= comment.user.first_name %></p> 
					</td>
					<td> 
					<% if current_user.id == comment.user.id %>
						<a class="btn btn-primary btn-sm" href="<%= edit_comment_path(comment.id) %>" role="button">Modifier le commentaire</a> </td>
					<%end%>
					</tr>
					<%end %>
				</tbody>
		</table>
	
</section>