config/routes.rb
Rails.application.routes.draw do
	
  resources :likes
	root to: 'users#new'
	
	resources :contacts, only: [:new, :create]

	resources :team, only: [:index]

	resources :gosssips do
		resources :likes, only: [:create, :destroy]
	end

	resources :users

	resources :cities

	resources :tags, only: [:new, :create, :destroy]

	resources :comments, except: [:new, :index, :show]
	
	resources :sessions, only: [:new, :create, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
        validates :name, presence: true, word: true
        validates :zip_code, presence: true, text: true
	
	has_many :users        #City en relation 1-N avec User

end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence:true, text: true
    
    belongs_to :user
    belongs_to :gosssip
end

app/models/gosssip.rb
class Gosssip < ApplicationRecord
	validates :title, presence: true, text: true, length: {maximum: 14}
	validates :content, presence: true, text: true
	validates :user_id, presence: true, on: create
		

	belongs_to :user
	has_many :tag_lists
	has_many :tags, through: :tag_lists
	has_many :comments
	has_many :users, through: :comments
	has_many :likes, dependent: :destroy
	has_many :users, through: :likes

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :gosssip
	belongs_to :user

        def self.gossips(user_id)
            @likes_gossips = Array.new
            @likes = Like.where(user_id: user_id)
            @likes.each do |like|
                @likes_gossips << like.gosssip_id
            end
            return @likes_gossips
        end

end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title, presence: true
	#, format: { with: /\A$#[\w\_]{2,20}\z/, message: "format #hashtag entre 2 et 10 caracteres" }

	has_many :tag_lists
	has_many :gosssips, through: :tag_lists
end

app/models/tag_list.rb
class TagList < ApplicationRecord
	belongs_to :gosssip
	belongs_to :tag

end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Merci d'inserer un email valide" }
	validates :first_name, presence: true, word: true
	validates :last_name, word: true, on: :update
	validates :age, format: {with: /[0-9]{2}/, message: "l'age doit etre ecrit avec 2 chiffres"}, on: :update
	validates :description, text:true, on: :update
	validates :city_id, text: true, on: :update
	validates :password, presence: true, length: {minimum: 6} 
		
	has_secure_password
		
	belongs_to :city
	has_many :gosssips
	has_many :comments
	has_many :gosssips, through: :comments
	has_many :likes, dependent: :destroy
	has_many :gosssips, through: :likes

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def new
    end

    def create 
    end

    def destroy 
    end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    skip_before_action :only_signed_in, only: [:index]

    def index

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_helper.rb
module DynamicHelper
end

app/helpers/gosssips_helper.rb
module GosssipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id].nil?
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
         <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/71edf01ac1.js" crossorigin="anonymous"></script>

    
    <!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<header>
        	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                	<a class="navbar-brand" href="<%= gosssips_path %>">The Gossip Project</a>
                        	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                	<span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                                	<ul class="navbar-nav">
                                        	<li class="nav-item active">
                                                	<a class="nav-link" href="<%= gosssips_path %>">Accueil<span class="sr-only">(current)</span></a>
                                                </li>
                                                <li class="nav-item">
                                                        <a class="nav-link" href="<%= team_index_path %>">Team</a>
                                                </li>
                                                <li class="nav-item">
                                                        <a class="nav-link" href="<%= new_contact_path %>">Contact</a>
                                                </li>

                                        </ul>
                                </div>
                                <% if logged_in? %>
                                        <%= link_to "Se connecter", new_session_path, class: 'btn btn-success' %>
                                <% else %>
                                        <%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: 'btn btn-danger' %>
                                <%end%>
	</header>
                <div class="container-blue">
                        <div class="container" style="...">
                        <% flash.each do |name, msg| %>
                                <div class="alert alert-<%=name%>"> <%= msg %> </div>
                        <%end%>
                </div>
        </div>
			
		
		<%= yield %>

  
	  
	  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
<section class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Copyright © David 2019</small>
    </div>
  </section>
 
</html>